### ISSUE TITLE
TSC won't import 'typescript-dotnet-core' module

### ISSUE THREAD

**Issue by sharpninja** [electricessence/TypeScript.NET-Core#2]
> Executing task: e:\GitHub\ElectronCGI\CrossPipes\CrossPipes-TS\node_modules\.bin\tsc.cmd -p e:\GitHub\ElectronCGI\CrossPipes\CrossPipes-TS\tsconfig.json <
>
> CrossPipes-TS/src/pipe.ts:3:22 - error TS2307: Cannot find module 'typescript-dotnet-core'.
>
> import * as TDN from "typescript-dotnet-core";

This happens on two different computers.

You can see the code at [it's repository](https://github.com/sharpninja/crosspipes)

**Comment by imsergiobernal** [comment]
The same here.

**Comment by electricessence** [comment]
it is not possible to * TDN.
Each module is separate.  It will be some time before I create index files.
If you are looking for a specific class, most editors will discover them for you.
Try something like:
`LinkedList<T>` and it should find it for you.
Otherwise you can cherry pick what you want this way:
```ts
import LinkedList from 'typescript-dotnet-core/Collections/LinkedList'
```
Where each module points relatively to its dependencies.

**Comment by electricessence** [comment]
Working on a much better distribution of this library... Hang tight. :)

**Comment by electricessence** [comment]
@sharpninja @imsergiobernal 
This lib has been moved here:
https://github.com/tsdotnet
Enjoy.
